services:
    search.listener:
        class: Kix\SearchBundle\Service\SearchListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    search.indexer:
        class: Kix\SearchBundle\Service\SearchIndexer
        arguments: [ @service_container ]
